[tool.poetry]
name = "miryoku-zmk"
version = "0.1.0"
description = ""
authors = ["Patrick Lau <patricklyc@berkeley.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pcpp = "^1.30"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
